"""
ingest_events.py — Script to ingest events from JSONL into the API

This script reads the events.jsonl file generated by the detection
pipeline and POSTs them in batches to the API's /events/ingest endpoint.

Usage:
    python scripts/ingest_events.py [--api-url http://localhost:8000] [--events-file data/events.jsonl]
"""

import json
import argparse
import requests
import time


def ingest_events(api_url: str, events_file: str, batch_size: int = 100):
    """Read events from JSONL and send them to the API in batches.
    
    Args:
        api_url: Base URL of the API (e.g., http://localhost:8000)
        events_file: Path to the events.jsonl file
        batch_size: Number of events per API call (max 500)
    """
    # Read all events from the JSONL file
    events = []
    with open(events_file, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    events.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Warning: Skipping malformed line: {e}")

    print(f"Loaded {len(events)} events from {events_file}")

    # Send events in batches
    total_accepted = 0
    total_rejected = 0
    ingest_url = f"{api_url}/events/ingest"

    for i in range(0, len(events), batch_size):
        batch = events[i:i + batch_size]

        try:
            response = requests.post(
                ingest_url,
                json={"events": batch},
                timeout=30,
            )

            if response.status_code == 200:
                result = response.json()
                total_accepted += result.get("accepted", 0)
                total_rejected += result.get("rejected", 0)
                print(
                    f"  Batch {i // batch_size + 1}: "
                    f"accepted={result['accepted']}, "
                    f"rejected={result['rejected']}"
                )
            else:
                print(f"  Batch {i // batch_size + 1}: ERROR {response.status_code}")
                print(f"    {response.text[:200]}")

        except requests.exceptions.ConnectionError:
            print(f"ERROR: Cannot connect to API at {api_url}")
            print("Make sure the API is running: uvicorn app.main:app --reload")
            return
        except Exception as e:
            print(f"  Batch {i // batch_size + 1}: ERROR {e}")

        # Small delay between batches to avoid overwhelming the API
        time.sleep(0.1)

    print(f"\nIngestion complete:")
    print(f"  Total accepted: {total_accepted}")
    print(f"  Total rejected: {total_rejected}")
    print(f"  Total events: {len(events)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ingest events into the API")
    parser.add_argument(
        "--api-url", default="http://localhost:8000",
        help="API base URL (default: http://localhost:8000)"
    )
    parser.add_argument(
        "--events-file", default="data/events.jsonl",
        help="Path to events JSONL file (default: data/events.jsonl)"
    )
    parser.add_argument(
        "--batch-size", type=int, default=100,
        help="Events per batch (default: 100, max: 500)"
    )
    args = parser.parse_args()

    ingest_events(args.api_url, args.events_file, args.batch_size)
